export const Questions = [
  {
    id: "q1",
    text: "What is Terraform?",
    answers: [
      "An Infrastructure as Code (IaC) tool",
      "A virtual machine software",
      "A cloud provider",
      "A container orchestration platform",
    ],
  },
  {
    id: "q2",
    text: "Who developed Terraform?",
    answers: ["HashiCorp", "Microsoft", "Amazon", "Google"],
  },
  {
    id: "q3",
    text: "What language is used to write Terraform configuration files?",
    answers: ["HashiCorp Configuration Language (HCL)", "YAML", "JSON", "XML"],
  },
  {
    id: "q4",
    text: "What is the file extension for Terraform configuration files?",
    answers: [".tf", ".terra", ".tfm", ".hcl"],
  },
  {
    id: "q5",
    text: "What command is used to initialize a Terraform working directory?",
    answers: [
      "terraform init",
      "terraform start",
      "terraform create",
      "terraform setup",
    ],
  },
  {
    id: "q6",
    text: "What command is used to preview the changes Terraform will make?",
    answers: [
      "terraform plan",
      "terraform preview",
      "terraform show",
      "terraform check",
    ],
  },
  {
    id: "q7",
    text: "What command applies the changes required to reach the desired state?",
    answers: [
      "terraform apply",
      "terraform execute",
      "terraform run",
      "terraform start",
    ],
  },
  {
    id: "q8",
    text: "What file stores the state of the Terraform-managed infrastructure?",
    answers: [
      "terraform.tfstate",
      "terraform.state",
      "terraform.config",
      "terraform.lock",
    ],
  },
  {
    id: "q9",
    text: "What are Terraform providers?",
    answers: [
      "Plugins that allow Terraform to interact with cloud providers, SaaS providers, and APIs",
      "Companies that offer Terraform support",
      "Individuals who write Terraform code",
      "Virtual machines that run Terraform operations",
    ],
  },
  {
    id: "q10",
    text: "What Terraform command is used to destroy infrastructure?",
    answers: [
      "terraform destroy",
      "terraform delete",
      "terraform remove",
      "terraform clean",
    ],
  },
  {
    id: "q11",
    text: "What defines a collection of related resources in Terraform?",
    answers: ["Module", "Template", "Package", "Cluster"],
  },
  {
    id: "q12",
    text: "What is the purpose of Terraform workspaces?",
    answers: [
      "To manage multiple distinct sets of infrastructure resources with the same configuration",
      "To collaborate with team members",
      "To store Terraform configurations",
      "To back up Terraform state files",
    ],
  },
  {
    id: "q13",
    text: "Which command validates the syntax of Terraform files?",
    answers: [
      "terraform validate",
      "terraform check",
      "terraform verify",
      "terraform lint",
    ],
  },
  {
    id: "q14",
    text: "What is the purpose of a Terraform 'data source'?",
    answers: [
      "To fetch or compute values from external sources for use in Terraform configurations",
      "To store secrets securely",
      "To define custom providers",
      "To back up Terraform state",
    ],
  },
  {
    id: "q15",
    text: "What is Terraform Cloud?",
    answers: [
      "A service that provides remote state management, version control integration, and more",
      "A cloud provider managed by HashiCorp",
      "A virtual machine image with Terraform pre-installed",
      "A physical data center for Terraform operations",
    ],
  },
  {
    id: "q16",
    text: "What is a Terraform backend?",
    answers: [
      "A component that determines how Terraform state is stored and accessed",
      "The backend infrastructure managed by Terraform",
      "The Terraform UI",
      "A Terraform repository",
    ],
  },
  {
    id: "q17",
    text: "What command formats Terraform configuration files to a canonical format?",
    answers: [
      "terraform fmt",
      "terraform format",
      "terraform style",
      "terraform lint",
    ],
  },
  {
    id: "q18",
    text: "What is the 'count' parameter used for in Terraform?",
    answers: [
      "To create multiple instances of a resource",
      "To count the number of resources",
      "To set a timeout value",
      "To specify the number of attempts",
    ],
  },
  {
    id: "q19",
    text: "What is a Terraform output?",
    answers: [
      "A value that is exposed by a Terraform module for external use",
      "The log files generated by Terraform",
      "The console output during execution",
      "The error messages from failed operations",
    ],
  },
  {
    id: "q20",
    text: "What is the purpose of a Terraform provider version constraint?",
    answers: [
      "To ensure compatibility with a specific version of a provider",
      "To limit the number of provider instances",
      "To restrict access to provider features",
      "To optimize provider performance",
    ],
  },
];
